name: flutter_advanced_networkimage
description: An advanced image provider provides caching and retrying for flutter app. Now with zoomable widget and transition to image widget.
version: 0.6.0
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  path_provider: ^2.0.2
  path: ^1.8.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"
